sonar.projectKey=Dona-Be_DonaBe
sonar.organization=dona-be
sonar.host.url=https://sonarcloud.io
sonar.projectName=DonaBe
sonar.sourceEncoding=UTF-8

sonar.sources=server/src,web/src
sonar.tests=server/tests,web/tests
sonar.coverage.exclusions=web/src/main.tsx

sonar.python.version=3.12
sonar.python.coverage.reportPaths=server/coverage.xml
sonar.javascript.lcov.reportPaths=web/coverage/lcov.info

sonar.qualitygate.wait=true
